### ISSUE TITLE
Debugging suggestion

### ISSUE THREAD

**Issue by rafaelfranca** [rails/sprockets#179]
_From @djvs on April 15, 2015 19:59_

Noticing in:

https://github.com/sstephenson/sprockets/blob/master/lib/sprockets/processed_asset.rb

in "initialize", it only tells you when an asset is done compiling, not when it is starting compilation.  Maybe you could write both?  At the moment, I am trying to debug this error:

    NoMethodError: undefined method `bytesize' for nil:NilClass
    [...] ruby-2.2.0/gems/rack-1.6.0/lib/rack/utils.rb:361:in `bytesize'
    [...] ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:13:in `initialize'

which is proving extremely difficult without knowing what file is being precompiled.  I often use "doing ..." and then "done" in my scripts, this is possible to do on the same line as well.

_Copied from original issue: sstephenson/sprockets#718_

**Comment by rafaelfranca** [comment]
_From @djvs on April 16, 2015 0:30_

In the end the error turned out to be a corrupted (first line had Rails 3 syntax in a Rails 4 app) config/environments/production.rb.  

Maybe, at bare minimum, you could do a begin/rescue/end block which catches the name of the failing asset that's compiling?

**Comment by rafaelfranca** [comment]
_From @schneems on August 28, 2015 17:22_

If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment]
Closing due to inactivity.

**Comment by choonkeat** [comment]
Can we open this? I'd suggest a small tweak

``` diff
diff --git a/lib/sprockets/loader.rb b/lib/sprockets/loader.rb
index 1eb2fb0..307a0a5 100644
--- a/lib/sprockets/loader.rb
+++ b/lib/sprockets/loader.rb
@@ -60,6 +60,9 @@ module Sprockets
         end
       end
       Asset.new(asset)
+    rescue Exception
+      puts uri.inspect
+      raise
     end
 
     private
```

by just showing me what file we're talking about.. this had helped me track down several errors (js came from some theme which had barfed utf8 and other weird cases).

cc @djvs

**Comment by aledalgrande** [comment]
@choonkeat there is discussion about this in #282
