### ISSUE TITLE
uninitialized constant ActiveSupport::TimeWithZone on assets:precompile

### ISSUE THREAD

**Issue by Ch4s3** [rails/sprockets#293]
During a build on CI, we ran into this error: `uninitialized constant ActiveSupport::TimeWithZone`

here is the full trace:

````
vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/core_ext/time/calculations.rb:42:in `at_with_coercion': uninitialized constant ActiveSupport::TimeWithZone (NameError)
    from vendor/bundle/jruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:216:in `mtime'
    from vendor/bundle/jruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/asset.rb:170:in `write_to'
    from vendor/bundle/jruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:192:in `block in compile'
    from vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.1-java/lib/concurrent/executor/safe_task_executor.rb:24:in `call'
    from vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.1-java/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
    from vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.1-java/lib/concurrent/executor/safe_task_executor.rb:19:in `synchronize'
    from vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.1-java/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
    from vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.1-java/lib/concurrent/ivar.rb:170:in `safe_execute'
    from vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.1-java/lib/concurrent/future.rb:52:in `block in execute'
    from vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.1-java/lib/concurrent/executor/java_executor_service.rb:94:in `call'
    from vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.1-java/lib/concurrent/executor/java_executor_service.rb:94:in `run'
````

**Comment by arthurnn** [comment]
Not sure how this is happening as the import exists https://github.com/rails/rails/blob/v4.2.6/activesupport/lib/active_support/core_ext/time/calculations.rb#L3

**Comment by Ch4s3** [comment]
I thought the same thing. It looked like it was blowing up in the call to Concurrent::Future. Very odd.

**Comment by schneems** [comment]
Make sure you have concurrent-ruby 1.0.1+

If it is still happening can you give me a repro example app?

**Comment by Ch4s3** [comment]
I am on concurrent-ruby 1.0.1. I have been unable to produce this since.
