### ISSUE TITLE
ActiveSupport::SafeBuffer not supported as digest class

### ISSUE THREAD

**Issue by zdraganov** [rails/sprockets#33]
When I've updated from 2.11.3 to 3.0.2 and running `rake assets:precompile` I receive the following error:
```
TypeError: couldn't digest ActiveSupport::SafeBuffer
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/digest_utils.rb:83:in `digest'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/loader.rb:116:in `load_asset_by_uri'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/loader.rb:40:in `block in load'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/loader.rb:170:in `fetch_asset_from_dependency_cache'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/loader.rb:33:in `load'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/cached_environment.rb:47:in `yield'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/cached_environment.rb:47:in `load'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/base.rb:63:in `find_asset'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/base.rb:70:in `find_all_linked_assets'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/manifest.rb:138:in `block in find'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:223:in `block in stat_tree'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:207:in `block in stat_directory'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:204:in `each'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:204:in `stat_directory'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:222:in `stat_tree'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:226:in `block in stat_tree'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:207:in `block in stat_directory'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:204:in `each'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:204:in `stat_directory'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:222:in `stat_tree'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:226:in `block in stat_tree'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:207:in `block in stat_directory'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:204:in `each'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:204:in `stat_directory'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:222:in `stat_tree'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/legacy.rb:105:in `each'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/legacy.rb:104:in `each'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/manifest.rb:136:in `find'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/sprockets/manifest.rb:162:in `compile'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-3.0.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/zhivko/.rvm/gems/ruby-2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
```

Into `digest_utils.rb` I see that there's no check for that particular class so the TypeError exception is thrown.
When I've changed the check for the String class into `digest` function on line 53 to
```
if klass.is_a? String
  digest << obj
```
it worked.
I tested with 2.11.3 and 2.12.3 and it's working.

If you want me I can provide PR.

**Comment by josh** [comment]
Interesting. Are you using any HTML related extensions? Wondering where the `SafeBuffer` would be coming from.

> Into digest_utils.rb I see that there's no check for that particular class so the TypeError exception is thrown.

I think is just a symptom of another issue here. Its likely that if a `ActiveSupport::SafeBuffer` is being cached, it may loose its subtype when its deserialized. All the cached types are supposed to be simple JSON for that reason. So depending on if its returned directly or from cache you might get different types. That can then affect any string operations down the line if another string gets appended to this buffer, it might be escaped.

Would like to know where this `ActiveSupport::SafeBuffer` is actually coming from. If its extension related, it probably wants to return a proper `to_str`. I wonder if its coming from Sprockets' own ERB class somehow. We'd definitely want to patch there.

While your hunting that down, I at least want to improve the error message in this case. It should probably say something like "data was expected to be a String, not ActiveSupport::SafeBuffer further up the stack". I'll work on that bit.

**Comment by kamen-hursev** [comment]
If you think it will be helpful here is a small app that reproduces the issue: https://github.com/kamen-hursev/test-sprockets. It is a new rails project with added haml as assets engine and in `home.js.erb` I try to get the path to a haml file.

**Comment by josh** [comment]
Ah, haml, okay. Let me dig into the adapter they are using there.

**Comment by josh** [comment]
Added a better error message here https://github.com/rails/sprockets/commit/aa37ffd5fb311f176f715dc0a68f67b40f85fde7

**Comment by josh** [comment]
Proposed a fix over in https://github.com/rails/sprockets/pull/34. Would love confirmation that it actually works.
