### ISSUE TITLE
Tests failing due assets not being in the pipeline

### ISSUE THREAD

**Issue by NekoNova** [rails/sprockets#380]
### Expected behavior

I expect my tests to succeed without throwing an error that `application.js` is not part of the assets pipeline.

### Actual behavior

I'm in the process of upgrading to the latest sprockets 3.7.0 version.
I've fired up the application locally after setting the new configuration options for the application:

```
config.assets.unknown_asset_fallback = false
config.assets.quiet = true
```

The application itself works fine. I can browse to any page that I want and all functionality as well as the assets are being loaded properly. However when I run our rspec tests, they fail with the following error:

```
ActionView::Template::Error: The asset "application.js" is not present in the asset pipeline.
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/sprockets-rails-3.2.0/lib/sprockets/rails/helper.rb:83:in `compute_asset_path'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/helpers/asset_url_helper.rb:245:in `javascript_path'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/teaspoon-1.1.5/lib/teaspoon/engine.rb:113:in `block in javascript_include_tag'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/teaspoon-1.1.5/lib/teaspoon/engine.rb:111:in `map'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/teaspoon-1.1.5/lib/teaspoon/engine.rb:111:in `javascript_include_tag'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/sprockets-rails-3.2.0/lib/sprockets/rails/helper.rb:156:in `block in javascript_include_tag'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/sprockets-rails-3.2.0/lib/sprockets/rails/helper.rb:154:in `map'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/sprockets-rails-3.2.0/lib/sprockets/rails/helper.rb:154:in `javascript_include_tag'
./app/views/layouts/admin.html.erb:8:in `_app_views_layouts_admin_html_erb___2941740872354185854_70312059497280'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in `block in render'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/template.rb:333:in `instrument'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/template.rb:143:in `render'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:46:in `render_template'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:27:in `render'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:100:in `_render_template'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:83:in `render_to_body'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/abstract_controller/rendering.rb:25:in `render'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:16:in `render'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/test_case.rb:639:in `process'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/test_case.rb:67:in `process'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/devise-4.2.0/lib/devise/test/controller_helpers.rb:33:in `block in process'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/devise-4.2.0/lib/devise/test/controller_helpers.rb:100:in `catch'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/devise-4.2.0/lib/devise/test/controller_helpers.rb:100:in `_catch_warden'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/devise-4.2.0/lib/devise/test/controller_helpers.rb:33:in `process'
/Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/actionpack-4.2.7.1/lib/action_controller/test_case.rb:514:in `get'
./spec/controllers/admins/admins_controller_spec.rb:40:in `block (4 levels) in <top (required)>'
./spec/rails_helper.rb:120:in `block (3 levels) in <top (required)>'
./spec/rails_helper.rb:73:in `with_transaction'
./spec/rails_helper.rb:119:in `block (2 levels) in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'
------------------
--- Caused by: ---
Sprockets::Rails::Helper::AssetNotFound:
  The asset "application.js" is not present in the asset pipeline.
  /Users/olivar/.rvm/gems/ruby-2.3.1@riskmethods/gems/sprockets-rails-3.2.0/lib/sprockets/rails/helper.rb:83:in `compute_asset_path'
```

I'm a bit at a loss here, but my gut feeling says this might be a combination of teaspoon and sprockets in our tests. I tried check with teaspoon if I could find an update or anything related, but nothing immediately popped out for me.

### System configuration

- Sprockets version : 3.7.0
- Ruby version : 2.3.1

**Comment by NekoNova** [comment]
okay,

this can be closed.
The problem is related to `sprockets-rails` which already has an issue open for Teaspoon to work on this
