### ISSUE TITLE
Coffee and SCSS preprocessors not getting called when used in Gem with Rails

### ISSUE THREAD

**Issue by tomprats** [rails/sprockets#423]
### Expected behavior

I expect the Gem for Coffee to raise an error when the App for Coffee tries to transform the test.coffee to javascript. I have the same code but for CSS and using a CSS test file that does raise an error.

### Actual behavior

The preprocessor doesn't get called in the Coffee example, but does in the CSS example. I added a SCSS example and it looks like it doesn't get called either. I may be understanding things wrong about how to add a preprocessor for such types

### System configuration

- Sprockets 3.7.0
- Ruby 2.3.1p112

### Example App

App for Coffee: https://github.com/tomprats/sprockets-test/tree/coffee
Gem for Coffee: https://github.com/tomprats/sprockets-cjsx/blob/sprockets-test-coffee/lib/sprockets-cjsx.rb

Working App for CSS: https://github.com/tomprats/sprockets-test/tree/alt
Working Gem for CSS: https://github.com/tomprats/sprockets-cjsx/blob/sprockets-test-alt/lib/sprockets-cjsx.rb

**Comment by schneems** [comment]
Sorry for the outragenous delay here.

With your gem I get an exception

```
$ be rake assets:precompile
/Users/rschneeman/.gem/ruby/2.4.2/gems/activesupport-5.0.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/Users/rschneeman/.gem/ruby/2.4.2/gems/activesupport-5.0.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'sprockets-cjsx'.
Gem Load Error is: undefined local variable or method `config' for main:Object
Backtrace for gem load error is:
/Users/rschneeman/.gem/ruby/2.4.2/gems/sprockets-4.0.0.beta6/lib/sprockets/processing.rb:215:in `register_config_processor'
/Users/rschneeman/.gem/ruby/2.4.2/gems/sprockets-4.0.0.beta6/lib/sprockets/processing.rb:54:in `register_preprocessor'
/Users/rschneeman/.gem/ruby/2.4.2/bundler/gems/sprockets-cjsx-9b647abb29e3/lib/sprockets-cjsx.rb:11:in `<top (required)>'
/Users/rschneeman/.gem/ruby/2.4.2/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `require'
/Users/rschneeman/.gem/ruby/2.4.2/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/rschneeman/.gem/ruby/2.4.2/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `each'
/Users/rschneeman/.gem/ruby/2.4.2/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `block in require'
/Users/rschneeman/.gem/ruby/2.4.2/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
/Users/rschneeman/.gem/ruby/2.4.2/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
/Users/rschneeman/.gem/ruby/2.4.2/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
/private/tmp/sprockets-test/config/application.rb:7:in `<top (required)>'
/private/tmp/sprockets-test/Rakefile:4:in `require_relative'
/private/tmp/sprockets-test/Rakefile:4:in `<top (required)>'
```

Without your gem it works for me with sprockets 4.0.0.beta6. I run `rake assets:precompile` and I get a `test-1e19fd6f71f3c663e436c05b178420a7c13c7acf8e6a45bb9a9ffef4b593e765.js` file generated.

> I expect the Gem for Coffee to raise an error when the App for Coffee tries to transform the test.coffee to javascript.

Why would you expect an error to be raised?
