### ISSUE TITLE
Trouble working with dot-notated filenames

### ISSUE THREAD

**Issue by lessthanzero** [rails/sprockets#428]
### Expected behavior

I am using [jekyll-assets](https://github.com/jekyll/jekyll-assets) (its pipeline is based on sprockets) for my website assets handling. I link js and css files in my template via `{% js example %}` liquid notation.

### Actual behavior

When I link `example.js` file, it works fine, but when I try to link something like `jquery.example.js` (`{% js jquery.example %}`) — file with dots in its name, jekyll-assets can't find the file. 
`//= require jquery.example.js` inside my app.js file doesn't work either.

I've started a thread [here](https://github.com/jekyll/jekyll-assets/issues/350) and wanted to check here too, to see whether it's an intended behavior or a bug. Thanks for any hints!

### System configuration

- Sprockets version 3.7.0
- Ruby version 2.3.0p0

**Comment by schneems** [comment]
I use `jekyll-assets` too. Can you give me an example app that reproduces the problem?

**Comment by lessthanzero** [comment]
@schneems hi. Here's a sample repo mimicking my working project: https://github.com/lessthanzero/sample-jekyll

Clone it and run the commands from readme. By default, it works fine linking `pressure.js` (as seen in inspector), but if you uncomment `jquery.pressure` it all goes haywire.

**Comment by schneems** [comment]
I couldn't get your program running

```
$ bundle install; npm i; bower install; gulp
Using public_suffix 2.0.4
Using babel-source 5.8.35
Using colorator 1.1.0
Using concurrent-ruby 1.0.2
Using forwardable-extended 2.6.0
Using ffi 1.9.14
Using sass 3.4.22
Using execjs 2.7.0
Using rb-fsevent 0.9.8
Using kramdown 1.13.1
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using rack 1.6.4
Using jekyll-paginate 1.1.0
Using bundler 1.13.6
Using addressable 2.5.0
Using extras 0.1.0
Using pathutil 0.14.0
Using rb-inotify 0.9.7
Using jekyll-sass-converter 1.5.0
Using babel-transpiler 0.7.0
Using sprockets 3.6.3
Using fastimage 2.0.0
Using listen 3.0.8
Using sprockets-es6 0.9.2
Using jekyll-watch 1.5.0
Using jekyll 3.3.1
Using jekyll-assets 2.2.8
Using jekyll-feed 0.8.0
Using minima 2.1.0
Bundle complete! 6 Gemfile dependencies, 32 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
npm WARN sample-jekyll@1.0.0 No repository field.
module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
-bash: gulp: command not found
2.4.0  ~/documents/projects/tmp/sample-jekyll (master)
$
2.4.0  ~/documents/projects/tmp/sample-jekyll (master)
$ chruby 2.3.3
Ignoring atomic-1.1.14 because its extensions are not built.  Try: gem pristine atomic --version 1.1.14
Ignoring bcrypt-3.1.11 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.11
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring bcrypt-ruby-3.1.2 because its extensions are not built.  Try: gem pristine bcrypt-ruby --version 3.1.2
Ignoring bcrypt-ruby-3.0.1 because its extensions are not built.  Try: gem pristine bcrypt-ruby --version 3.0.1
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring bluecloth-2.2.0 because its extensions are not built.  Try: gem pristine bluecloth --version 2.2.0
Ignoring byebug-9.0.5 because its extensions are not built.  Try: gem pristine byebug --version 9.0.5
Ignoring byebug-8.2.4 because its extensions are not built.  Try: gem pristine byebug --version 8.2.4
Ignoring byebug-8.2.2 because its extensions are not built.  Try: gem pristine byebug --version 8.2.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring byebug-8.2.0 because its extensions are not built.  Try: gem pristine byebug --version 8.2.0
Ignoring byebug-6.0.2 because its extensions are not built.  Try: gem pristine byebug --version 6.0.2
Ignoring byebug-5.0.0 because its extensions are not built.  Try: gem pristine byebug --version 5.0.0
Ignoring byebug-3.4.0 because its extensions are not built.  Try: gem pristine byebug --version 3.4.0
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
2.3.3  ~/documents/projects/tmp/sample-jekyll (master)
$ bundle install; npm i; bower install; gulp
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 2.0.4
Using babel-source 5.8.35
Using execjs 2.7.0
Using colorator 1.1.0
Using concurrent-ruby 1.0.2
Using forwardable-extended 2.6.0
Using ffi 1.9.14
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using rack 1.6.4
Using jekyll-paginate 1.1.0
Using bundler 1.13.6
Using addressable 2.5.0
Using babel-transpiler 0.7.0
Using extras 0.1.0
Using pathutil 0.14.0
Using rb-inotify 0.9.7
Using jekyll-sass-converter 1.5.0
Using sprockets 3.6.3
Installing fastimage 2.0.0
Using listen 3.0.8
Installing kramdown 1.13.1
Installing sprockets-es6 0.9.2
Using jekyll-watch 1.5.0
Installing jekyll 3.3.1
Using jekyll-assets 2.2.8
Installing minima 2.1.0
Installing jekyll-feed 0.8.0
Bundle complete! 6 Gemfile dependencies, 32 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from minima:

----------------------------------------------
Thank you for installing minima 2.0!

Minima 2.0 comes with a breaking change that
renders '<your-site>/css/main.scss' redundant.
That file is now bundled with this gem as
'<minima>/assets/main.scss'.

More Information:
https://github.com/jekyll/minima#customization
----------------------------------------------

npm WARN sample-jekyll@1.0.0 No repository field.
module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
-bash: gulp: command not found
2.3.3  ~/documents/projects/tmp/sample-jekyll (master)
$
```

I tried to reproduce on my own app: github.com/schneems/schneems

Added a `assets/javascripts/jquery.example.js` then in my head added a `  {% js 'jquery.example.js' %}` and it worked just fine.

**Comment by lessthanzero** [comment]
@schneems great, thanks, it helped me to narrow down problem a bit. Yes, it works fine when you add files to, say, `assets/js`. But breaks when you have bower distros inside `assets/bower/` and want to link files from distros: in that situation {% js bower-example %} works and {% js jquery.bower-example %} – don't.

Btw seems like you've faced some sort of problem with `bower` or `npm`, but nevermind.

**Comment by schneems** [comment]
You ever get this working?

**Comment by joemsak** [comment]
Any chance someone can give insight on this issue? I have a brand new rails 6.1.1 app with sprockets 4 (not explicit in the Gemfile, but is present in the Gemfile.lock) and requiring a file with dots in the names is failing. If I rename the file, it will get included fine.

Here is my repo https://github.com/joemsak/dot-notated-files-in-rails - the file is in the vendor/assets folder as I am mimicking how this works in a legacy project my team is trying to upgrade.

Here is the application.js top-level file https://github.com/joemsak/dot-notated-files-in-rails/blob/main/app/assets/javascripts/application.js

If I rename the file without dots in the name, the app loads and the file is there in my developer tools sources.

Thanks in advance for any help anyone can provide, I have searched google as much as humanly possible and asked for help on codementor.io but no dice.
