### ISSUE TITLE
NoMethodError - undefined method `set' for #<ThreadSafe::Cache:0x007f8514012fc0>

### ISSUE THREAD

**Issue by vanso-hubsi** [rails/sprockets#431]
### Expected behavior

No exception thrown

### Actual behavior

I just updated the gems of my Rails application. Now when I load the index page after having started rails server, I get the following exception:

```
NoMethodError - undefined method `set' for #<ThreadSafe::Cache:0x007f8514012fc0>:
  sprockets (3.6.3) lib/sprockets/cache.rb:212:in `set'
  sprockets (3.6.3) lib/sprockets/cache.rb:86:in `fetch'
  sprockets (3.6.3) lib/sprockets/base.rb:56:in `file_digest'
  sprockets (3.6.3) lib/sprockets/unloaded_asset.rb:104:in `dependency_history_key'
  sprockets (3.6.3) lib/sprockets/loader.rb:304:in `fetch_asset_from_dependency_cache'
  sprockets (3.6.3) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.6.3) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.6.3) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.6.3) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (3.6.3) lib/sprockets/base.rb:92:in `[]'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:355:in `find_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:336:in `digest_path'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:325:in `asset_path'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:102:in `block in resolve_asset_path'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `resolve_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:101:in `resolve_asset_path'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
  actionview (4.2.7.1) lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
  actionview (4.2.7.1) lib/action_view/helpers/asset_url_helper.rb:292:in `image_path'
  actionview (4.2.7.1) lib/action_view/helpers/asset_tag_helper.rb:211:in `image_tag'
  app/views/layouts/_login.haml:3:in `_app_views_layouts__login_haml__2388036641888989102_70104772216880'
[...]
```

I haven't found anyone else with this error, so I'm opening this issue.

### System configuration

- Sprockets version 3.6.3
- Ruby version 2.1.2

**Comment by vanso-hubsi** [comment]
With some deeper investigation I found out that it was my own fault. I had the following old lines in my application.rb:
```
    config.assets.configure do |env|
      env.cache = ThreadSafe::Cache.new
    end
```
which I changed to
```
    config.assets.configure do |env|
      env.cache = ActiveSupport::Cache.lookup_store(:memory_store, { size: 32.megabytes })
    end
```
and now it works.
