### ISSUE TITLE
Beta4: undefined method "format_source_maps"

### ISSUE THREAD

**Issue by antoniusostermann** [rails/sprockets#463]
### Expected behavior

I have been following this guide: http://9elements.com/io/babel-rails-5-and-sprockets-4/ to use Sprockets in combination with sprockets-commoner and babel to enable es6 modules. I am trying to install and setup everything, but my app does not start anymore after using a `manifest.js`.

### Actual behavior

If I use PUMA:
```
An ActionView::Template::Error occurred in sites#none:

  undefined method `format_source_map' for Sprockets::SourceMapUtils:Module
Did you mean?  format
               concat_source_maps
  app/assets/config/manifest.js:2
```
```
NoMethodError - undefined method `format_source_map' for Sprockets::SourceMapUtils:Module
Did you mean?  format
               concat_source_maps:
  sprockets (4.0.0.beta4) lib/sprockets/directive_processor.rb:183:in `rescue in block in process_directives'
  sprockets (4.0.0.beta4) lib/sprockets/directive_processor.rb:180:in `block in process_directives'
  sprockets (4.0.0.beta4) lib/sprockets/directive_processor.rb:179:in `process_directives'
  sprockets (4.0.0.beta4) lib/sprockets/directive_processor.rb:80:in `_call'
  sprockets (4.0.0.beta4) lib/sprockets/directive_processor.rb:65:in `call'
  sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:84:in `call_processor'
  sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:66:in `block in call_processors'
  sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:65:in `call_processors'
  sprockets (4.0.0.beta4) lib/sprockets/loader.rb:148:in `load_from_unloaded'
  sprockets (4.0.0.beta4) lib/sprockets/loader.rb:59:in `block in load'
  sprockets (4.0.0.beta4) lib/sprockets/loader.rb:324:in `fetch_asset_from_dependency_cache'
  sprockets (4.0.0.beta4) lib/sprockets/loader.rb:43:in `load'
  sprockets (4.0.0.beta4) lib/sprockets/cached_environment.rb:21:in `block in initialize'
  sprockets (4.0.0.beta4) lib/sprockets/cached_environment.rb:48:in `load'
  sprockets (4.0.0.beta4) lib/sprockets/bundle.rb:24:in `block in call'
  sprockets (4.0.0.beta4) lib/sprockets/utils.rb:166:in `dfs'
  sprockets (4.0.0.beta4) lib/sprockets/bundle.rb:25:in `call'
  sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:84:in `call_processor'
  sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:66:in `block in call_processors'
  sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:65:in `call_processors'
  sprockets (4.0.0.beta4) lib/sprockets/loader.rb:148:in `load_from_unloaded'
  sprockets (4.0.0.beta4) lib/sprockets/loader.rb:59:in `block in load'
  sprockets (4.0.0.beta4) lib/sprockets/loader.rb:324:in `fetch_asset_from_dependency_cache'
  sprockets (4.0.0.beta4) lib/sprockets/loader.rb:43:in `load'
  sprockets (4.0.0.beta4) lib/sprockets/cached_environment.rb:21:in `block in initialize'
  sprockets (4.0.0.beta4) lib/sprockets/cached_environment.rb:48:in `load'
  sprockets (4.0.0.beta4) lib/sprockets/base.rb:67:in `find_asset'
  sprockets (4.0.0.beta4) lib/sprockets/base.rb:74:in `find_all_linked_assets'
  sprockets (4.0.0.beta4) lib/sprockets/manifest.rb:124:in `block in find'
  sprockets (4.0.0.beta4) lib/sprockets/manifest.rb:123:in `find'
  sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in `precompiled_assets'
  sprockets-rails (3.2.0) lib/sprockets/railtie.rb:35:in `asset_precompiled?'
  sprockets-rails (3.2.0) lib/sprockets/railtie.rb:251:in `block (3 levels) in <class:Railtie>'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:359:in `precompiled?'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:363:in `raise_unless_precompiled_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:348:in `find_debug_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:229:in `block in lookup_debug_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `resolve_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:228:in `lookup_debug_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:170:in `block in stylesheet_link_tag'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:169:in `stylesheet_link_tag'
  app/views/layouts/structure/_header.html.erb:7:in `_app_views_layouts_structure__header_html_erb__1008820885453572027_47237119587920'
```

```
bundle exec rails assets:precompile
NoMethodError: undefined method `format_source_map' for Sprockets::SourceMapUtils:Module
Did you mean?  format
               concat_source_maps
/app/assets/config/manifest.js:2
```

If I use Passenger + Nginx, I just get:
```
No such file or directory - node
```

Both points to my app/assets/config/manifest.js, which has:
```
//= link_tree ../images
//= link_directory ../javascripts .js
//= link_directory ../stylesheets .css
```
So there is something wrong with my javascript (line 2). My current application js is still using the old sprockets directives, so there is stuff like:
```
//= require_tree ./globals
//= require_tree ./components
```
I want to migrate to es6 module loading in parts from now.

### System configuration

- Sprockets Beta 4
- Rails 5
- Ruby 2.3.1p112

**Comment by antoniusostermann** [comment]
Error is gone if I choose master branch.
