### ISSUE TITLE
Problem with resolving paths for deeply nested assets

### ISSUE THREAD

**Issue by brandoncordell** [rails/sprockets#494]
I have an application that has admin namespaced controllers as my admin dashboard area. I'm trying to split up my assets so that they're namespaced as well, e.g. `stylesheets/admin/admin.css`, `javascripts/admin/admin.js`.

I've added `admin.js` and `admin.css` to the precompile list.

### Expected behavior

I would expect by requiring assets inside of `admin/admin.js` using `//= require admin/name-of-file` that it would load as normal. I have to prepend `admin/` because my load path is only `app/assets/javascripts` (for example).

### Actual behavior

It works for the most part, but certain assets (and also randomly...) I get `undefined method 'start_with?' for nil:NilClass`

When I follow the stack trace to `sprockets (4.0.0.beta4) lib/sprockets/resolve.rb:32:in 'resolve'` and add `binding.pry` as the page loads I can watch the paths resolve. 99% of them are fine, but certain assets end up returning with the path concatenated to itself.

Actual output of `resolve`

```
[nil,
 nil,
 nil,
 #<Set: {"file-digest:///Users/brandoncordell/Code/new_vjf/app/assets/config/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/app/assets/config/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/app/assets/fonts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/app/assets/fonts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/app/assets/images/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/app/assets/images/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/app/assets/javascripts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/app/assets/javascripts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/app/assets/stylesheets/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/app/assets/stylesheets/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/vendor/assets/javascripts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/vendor/assets/javascripts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/vendor/assets/stylesheets/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/vendor/assets/stylesheets/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/summernote-rails-0.8.3.0/vendor/assets/fonts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/summernote-rails-0.8.3.0/vendor/assets/fonts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/summernote-rails-0.8.3.0/vendor/assets/javascripts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/summernote-rails-0.8.3.0/vendor/assets/javascripts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/summernote-rails-0.8.3.0/vendor/assets/stylesheets/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/summernote-rails-0.8.3.0/vendor/assets/stylesheets/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/coffee-rails-4.2.2/lib/assets/javascripts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/coffee-rails-4.2.2/lib/assets/javascripts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actioncable-5.1.3.rc2/lib/assets/compiled/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actioncable-5.1.3.rc2/lib/assets/compiled/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionview-5.1.3.rc2/lib/assets/compiled/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionview-5.1.3.rc2/lib/assets/compiled/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/turbolinks-source-5.0.3/lib/assets/javascripts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/turbolinks-source-5.0.3/lib/assets/javascripts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/node_modules/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/Code/new_vjf/node_modules/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-sass-3.3.7/assets/stylesheets/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-sass-3.3.7/assets/stylesheets/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-sass-3.3.7/assets/javascripts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-sass-3.3.7/assets/javascripts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-sass-3.3.7/assets/fonts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-sass-3.3.7/assets/fonts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-sass-3.3.7/assets/images/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-sass-3.3.7/assets/images/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/font-awesome-sass-4.7.0/assets/stylesheets/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/font-awesome-sass-4.7.0/assets/stylesheets/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/font-awesome-sass-4.7.0/assets/fonts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin",
  "file-digest:///Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/font-awesome-sass-4.7.0/assets/fonts/Users/brandoncordell/Code/new_vjf/app/assets/javascripts/admin/admin"}>]
```

Stack Trace:

```
sprockets (4.0.0.beta4) lib/sprockets/path_utils.rb:141:in `split_subpath'
sprockets (4.0.0.beta4) lib/sprockets/path_utils.rb:156:in `block in paths_split'
sprockets (4.0.0.beta4) lib/sprockets/path_utils.rb:155:in `each'
sprockets (4.0.0.beta4) lib/sprockets/path_utils.rb:155:in `paths_split'
sprockets (4.0.0.beta4) lib/sprockets/resolve.rb:122:in `resolve_relative_path'
sprockets (4.0.0.beta4) lib/sprockets/resolve.rb:32:in `resolve'
sprockets (4.0.0.beta4) lib/sprockets/resolve.rb:47:in `resolve!'
sprockets (4.0.0.beta4) lib/sprockets/source_map_processor.rb:39:in `block in call'
sprockets (4.0.0.beta4) lib/sprockets/source_map_processor.rb:31:in `each'
sprockets (4.0.0.beta4) lib/sprockets/source_map_processor.rb:31:in `call'
sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:84:in `call_processor'
sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:66:in `block in call_processors'
sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:65:in `reverse_each'
sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:65:in `call_processors'
sprockets (4.0.0.beta4) lib/sprockets/loader.rb:148:in `load_from_unloaded'
sprockets (4.0.0.beta4) lib/sprockets/loader.rb:59:in `block in load'
sprockets (4.0.0.beta4) lib/sprockets/loader.rb:324:in `fetch_asset_from_dependency_cache'
sprockets (4.0.0.beta4) lib/sprockets/loader.rb:43:in `load'
sprockets (4.0.0.beta4) lib/sprockets/cached_environment.rb:21:in `block in initialize'
sprockets (4.0.0.beta4) lib/sprockets/cached_environment.rb:48:in `load'
sprockets (4.0.0.beta4) lib/sprockets/source_map_comment_processor.rb:22:in `call'
sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:84:in `call_processor'
sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:66:in `block in call_processors'
sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:65:in `reverse_each'
sprockets (4.0.0.beta4) lib/sprockets/processor_utils.rb:65:in `call_processors'
sprockets (4.0.0.beta4) lib/sprockets/loader.rb:148:in `load_from_unloaded'
sprockets (4.0.0.beta4) lib/sprockets/loader.rb:59:in `block in load'
sprockets (4.0.0.beta4) lib/sprockets/loader.rb:324:in `fetch_asset_from_dependency_cache'
sprockets (4.0.0.beta4) lib/sprockets/loader.rb:43:in `load'
sprockets (4.0.0.beta4) lib/sprockets/cached_environment.rb:21:in `block in initialize'
sprockets (4.0.0.beta4) lib/sprockets/cached_environment.rb:48:in `load'
sprockets (4.0.0.beta4) lib/sprockets/base.rb:67:in `find_asset'
sprockets (4.0.0.beta4) lib/sprockets/base.rb:93:in `[]'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:355:in `find_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:347:in `find_debug_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:229:in `block in lookup_debug_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `each'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `detect'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `resolve_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:228:in `lookup_debug_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:141:in `block in javascript_include_tag'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:140:in `map'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:140:in `javascript_include_tag'
app/views/layouts/admin.html.erb:53:in `_app_views_layouts_admin_html_erb__966477232447571415_70296862231080'
actionview (5.1.3.rc2) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.3.rc2) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.3.rc2) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.3.rc2) lib/action_view/template.rb:155:in `render'
actionview (5.1.3.rc2) lib/action_view/renderer/template_renderer.rb:64:in `render_with_layout'
actionview (5.1.3.rc2) lib/action_view/renderer/template_renderer.rb:50:in `render_template'
actionview (5.1.3.rc2) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.1.3.rc2) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.1.3.rc2) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.1.3.rc2) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.1.3.rc2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.1.3.rc2) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.1.3.rc2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.1.3.rc2) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (5.1.3.rc2) lib/abstract_controller/rendering.rb:24:in `render'
actionpack (5.1.3.rc2) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.1.3.rc2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.1.3.rc2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/brandoncordell/.rbenv/versions/2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
activesupport (5.1.3.rc2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.1.3.rc2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.1.3.rc2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.1.3.rc2) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
actionpack (5.1.3.rc2) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (5.1.3.rc2) lib/action_controller/metal/implicit_render.rb:33:in `default_render'
actionpack (5.1.3.rc2) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
actionpack (5.1.3.rc2) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
actionpack (5.1.3.rc2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.3.rc2) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.3.rc2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.3.rc2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.3.rc2) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.3.rc2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.3.rc2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.3.rc2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.3.rc2) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.3.rc2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.3.rc2) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.3.rc2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.3.rc2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.3.rc2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.3.rc2) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.3.rc2) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.3.rc2) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.3.rc2) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.3.rc2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.3.rc2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.3.rc2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.3.rc2) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.3.rc2) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.3.rc2) lib/action_dispatch/routing/route_set.rb:834:in `call'
bullet (5.6.0) lib/bullet/rack.rb:12:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.3.rc2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.3.rc2) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.3.rc2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.3.rc2) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.3.rc2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.3.rc2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.3.rc2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.3.rc2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.3.rc2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.3.rc2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.3.rc2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.3.rc2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.3.rc2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.3.rc2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.3.rc2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.3.rc2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.3.rc2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.3.rc2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.3.rc2) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.3.rc2) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```
### System configuration

- Sprockets 4.0.0.beta4
- Ruby 2.4.1p111
- Rails 5.1.3.rc2

### Example App

https://github.com/CTSATLAS/virtual_job_fair/

**Comment by brandoncordell** [comment]
Solved this by putting the admin manifests (`admin.scss` and `admin.js`) back into their respective root assets directories and then just importing/requiring the `admin` subfolder.
