### ISSUE TITLE
How to include a .css in production asset precompile without SASS pre-processing it?

### ISSUE THREAD

**Issue by abevoelker** [rails/sprockets#553]
I'd like to include a .css file in `app/assets/stylesheets/application.scss` that doesn't get processed as a SASS file. I'm including the latest version of jquery-ui.css, which has [a reference to the CSS function `rgba()` without any arguments](https://gist.github.com/abevoelker/59943df49c1ac1f6901ac14ccf616424#file-jquery-ui-css-L406). Unfortunately SASS also defines an rgba function which requires 4 arguments, so it errors out.

### Expected behavior

Including a .css file with:

```sass
/*
 *= require jquery-ui
 */
```

includes the .css as-is in the final application.css file without any SASS pre-processing

### Actual behavior

When running

```console
$ RAILS_ENV=production bundle exec rake assets:precompile
```

this error occurs:

```
Sass::SyntaxError: wrong number of arguments (0 for 4) for `rgba'
(sass):36446
/var/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:315:in `reformat_argument_error'
...
Caused by:
ArgumentError: wrong number of arguments (0 for 4)
/var/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/functions.rb:763:in `rgba'
/var/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:155:in `block in _perform'
...
```

### System configuration

- Sprockets version
3.7.1
- Ruby version
2.4.2
- Sass version
3.5.6

### Example App

https://github.com/abevoelker/sprockets-rgba

**Comment by abevoelker** [comment]
Closing because I think the .css file I was given shouldn't have that line in it - Chrome says in the inspector a bare rgba() call isn't valid. :expressionless:
