### ISSUE TITLE
Error on trying to precompile default assets from node_modules

### ISSUE THREAD

**Issue by ycherniavskyi** [rails/sprockets#567]
### Expected behavior

Sprockets should not try to precompile default assets (such as `application.js`, `application.css`, etc.) form `node_modules` folder, which added by Rails with webpack in `config/initializers/assets.rb` file by default.

### Actual behavior

During precompile assets of just created Rails application exception `Uglifier::Error: Unexpected token: punc ({). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true)` fired.

It happened because sprockets found `application.js` file in `stimulus` npm folder (actual path `node_modules/@stimulus/core/dist/module/src/application.js`), but could be in any other.

### System configuration

- Sprockets version: 3.7.2
- Ruby version: 2.5.1
- Rails version: 5.2.0

### Example App

```bash
$ rails new rails-stimulus-app --webpack=stimulus
$ cd rails-stimulus-app
$ RAILS_ENV=production rake assets:precompile
```

**Notice**: if change Rails default sprockets version to `4.0.0.beta8` then everything precompile without error.

### Related issue

rails/rails#33477

**Comment by schneems** [comment]
Thanks for the report I would recommend using Sprockets 4.

**Comment by ycherniavskyi** [comment]
For now, I just comment `Rails.application.config.assets.paths << Rails.root.join('node_modules')` line in `config/initializers/assets.rb`.

I open this issue to indicate that in the current Rails version, which delivered with Sprockets 3 and initialized with webpack, `assets:precompile` does not work out of the box.

**Comment by dawidlenkiewicz** [comment]
Is it possible that it still doesn't work with Sprockets 4? Rails 5.1.6

```
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.85s.
** Execute assets:precompile
rake aborted!
Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/uglifier-4.1.19/lib/uglifier.rb:234:in `parse_result'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/uglifier-4.1.19/lib/uglifier.rb:216:in `run_uglifyjs'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/uglifier-4.1.19/lib/uglifier.rb:178:in `compile_with_map'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/sprockets-4.0.0.beta8/lib/sprockets/uglifier_compressor.rb:58:in `call'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/sprockets-4.0.0.beta8/lib/sprockets/uglifier_compressor.rb:30:in `call'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/sprockets-4.0.0.beta8/lib/sprockets/processor_utils.rb:84:in `call_processor'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/sprockets-4.0.0.beta8/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/sprockets-4.0.0.beta8/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/sprockets-4.0.0.beta8/lib/sprockets/processor_utils.rb:65:in `call_processors'
```

**Comment by richjdsmith** [comment]
I'm in the same boat as @dawidlenkiewicz, running Rails 5.2.1 and still getting 

```Running: rake assets:precompile
remote:        yarn install v1.5.1
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        info fsevents@1.2.4: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning "@rails/webpacker > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
remote:        warning " > webpack-dev-server@2.11.2" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
remote:        warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
remote:        [4/4] Building fresh packages...
remote:        Done in 23.50s.
remote:        rake aborted!
remote:        Uglifier::Error: Unexpected token: operator (>). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
remote:        /tmp/build_af3baa654fdf3b70363446d7240401fa/vendor/bundle/ruby/2.5.0/gems/uglifier-4.1.19/lib/uglifier.rb:234:in `parse_result'
remote:        /tmp/build_af3baa654fdf3b70363446d7240401fa/vendor/bundle/ruby/2.5.0/gems/uglifier-4.1.19/lib/uglifier.rb:216:in `run_uglifyjs'
remote:        /tmp/build_af3baa654fdf3b70363446d7240401fa/vendor/bundle/ruby/2.5.0/gems/uglifier-4.1.19/lib/uglifier.rb:168:in `compile'
remote:        /tmp/build_af3baa654fdf3b70363446d7240401fa/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:53:in `call'
remote:        /tmp/build_af3baa654fdf3b70363446d7240401fa/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:28:in `call'
remote:        /tmp/build_af3baa654fdf3b70363446d7240401fa/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
```

Not really sure where to go. 

Here's my gemfile if it's any help:

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.1'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
gem 'mini_magick', '~> 4.8'

gem 'active_storage_drag_and_drop'

# Authentication - devise
gem 'devise'
# Role - Rolify Adds roles to users. - https://github.com/RolifyCommunity/rolify
# gem 'rolify', '~> 5.2'
# Authorization - Pundit
gem 'pundit', '~> 2.0'
# Administrate -  Used to add an admin dashboard - https://github.com/thoughtbot/administrate
gem "administrate"

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
 gem 'bootsnap', '>= 1.3.1', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # This will give me a better error page in development. Second is to support the first.
  gem "better_errors"
  gem "binding_of_caller"
  # Lets me view arays as tables
  gem 'table_print'
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
    # Adds pry, awesome print and Pry Cooline
  gem 'jazz_fingers'
  # Adds the pry-rails to add pry to rails
  gem 'pry-rails'
end


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by dawidlenkiewicz** [comment]
I'm not 100% sure when and how, but the issue is not happening since we moved to Rails 5.2.1 @richjdsmith

**Comment by richjdsmith** [comment]
It was still happening for me on a fresh install of Rails 5.2.1.

My solution was to ditch Sprockets all together.
