### ISSUE TITLE
x_sprockets_linecount not added in the source map

### ISSUE THREAD

**Issue by leleabhinav** [rails/sprockets#657]
### Expected behavior

Asset compilation should succeed for a javascript file.

`application.js`
```
var test;
```

This is used in a page which includes js using `<%= javascript_include_tag 'application' %>`. The asset is included in the manifest as below -

```
//= require application
//= link application.css
```

Now, I have a test case that is hitting the url `/`, expecting a `HTTP 200`. However the asset compilation fails as `x_sprockets_linecount` is not getting added to map hash in `source_map_utils.rb`.

### Actual behavior

I have tried to trace this issue a bit, but haven't got to the real cause of it. Below are traces generated by adding `puts` and `Tracepoint` in the execution.

```
"##reduceif data #<Proc:0x00007fd2fa20bcd0 (lambda)>"
"##reduceif map #<Proc:0x00007fd2f99840f8 (lambda)>"
"/Users/abhinavlele/.gem/ruby/2.5.1/gems/sprockets-4.0.0/lib/sprockets/source_map_utils.rb 73 Sprockets::SourceMapUtils concat_source_maps call"
 -- pre --
{"version"=>3, "file"=>"manifest.js", "sections"=>[]}
 ---
{"version"=>3, "file"=>"application.js", "mappings"=>";;;AAAA,MAAA,IAAA", "sources"=>["application.source.js"], "names"=>[]}
-- pre end --
"/Users/abhinavlele/.gem/ruby/2.5.1/gems/sprockets-4.0.0/lib/sprockets/source_map_utils.rb 144 Sprockets::SourceMapUtils make_index_map call"
"/Users/abhinavlele/.gem/ruby/2.5.1/gems/sprockets-4.0.0/lib/sprockets/source_map_utils.rb 145 Sprockets::SourceMapUtils make_index_map return {\"version\"=>3, \"file\"=>\"manifest.js\", \"sections\"=>[]}"
"/Users/abhinavlele/.gem/ruby/2.5.1/gems/sprockets-4.0.0/lib/sprockets/source_map_utils.rb 144 Sprockets::SourceMapUtils make_index_map call"
"/Users/abhinavlele/.gem/ruby/2.5.1/gems/sprockets-4.0.0/lib/sprockets/source_map_utils.rb 156 Sprockets::SourceMapUtils make_index_map return {\"version\"=>3, \"file\"=>\"application.js\", \"sections\"=>[{\"offset\"=>{\"line\"=>0, \"column\"=>0}, \"map\"=>{\"version\"=>3, \"file\"=>\"application.js\", \"mappings\"=>\";;;AAAA,MAAA,IAAA\", \"sources\"=>[\"application.source.js\"], \"names\"=>[]}}]}"
 -- post --
{"version"=>3, "file"=>"manifest.js", "sections"=>[]}
--
{"version"=>3, "file"=>"application.js", "sections"=>[{"offset"=>{"line"=>0, "column"=>0}, "map"=>{"version"=>3, "file"=>"application.js", "mappings"=>";;;AAAA,MAAA,IAAA", "sources"=>["application.source.js"], "names"=>[]}}]}
--post end--
"/Users/abhinavlele/.gem/ruby/2.5.1/gems/sprockets-4.0.0/lib/sprockets/source_map_utils.rb 113 Sprockets::SourceMapUtils concat_source_maps return {\"version\"=>3, \"file\"=>\"manifest.js\", \"sections\"=>[{\"offset\"=>{\"line\"=>0, \"column\"=>0}, \"map\"=>{\"version\"=>3, \"file\"=>\"application.js\", \"mappings\"=>\";;;AAAA,MAAA,IAAA\", \"sources\"=>[\"application.source.js\"], \"names\"=>[]}}]}"
"##reduceif commoner_enabled #<Proc:0x00007fd2f9aaeed8(&:|)>"
"##reduceif commoner_required #<Proc:0x00007fd2fa20ba50(&:+)>"
"##reduceif commoner_used_helpers #<Proc:0x00007fd2fa20ba50(&:+)>"
----- trace end -----
"## reducer {:data=>\"var __commoner_module__app$assets$javascripts$application_js = __commoner_initialize_module__(function (module, exports) {\\n  \\\"use strict\\\";\\n\\n  var test;\\n});\", :sources=>[], :map=>{\"version\"=>3, \"file\"=>\"manifest.js\", \"sections\"=>[{\"offset\"=>{\"line\"=>0, \"column\"=>0}, \"map\"=>{\"version\"=>3, \"file\"=>\"application.js\", \"mappings\"=>\";;;AAAA,MAAA,IAAA\", \"sources\"=>[\"application.source.js\"], \"names\"=>[]}}]}, :commoner_enabled=>true, :commoner_required=>#<Set: {}>, :commoner_used_helpers=>#<Set: {}>, :links=>#<Set: {}>} -- #<Sprockets::Asset:3fe97d975e04 \"file:///Users/abhinavlele/src/github.com/Shopify/identity_client/spec/dummy/app/assets/config/manifest.js?type=application/javascript&pipeline=self&id=48d1a5c6d071417c4d6815b3b6bf80e24e8878136c5a3d14bba3794dcf47fa2a\">"
"##reduceif data #<Proc:0x00007fd2fa20bcd0 (lambda)>"
"##reduceif links #<Proc:0x00007fd2fa20ba50(&:+)>"
"##reduceif map #<Proc:0x00007fd2f99840f8 (lambda)>"
 -- pre --
{"version"=>3, "file"=>"manifest.js", "sections"=>[{"offset"=>{"line"=>0, "column"=>0}, "map"=>{"version"=>3, "file"=>"application.js", "mappings"=>";;;AAAA,MAAA,IAAA", "sources"=>["application.source.js"], "names"=>[]}}]}
 ---
{"version"=>3, "file"=>"manifest.js", "mappings"=>"", "sources"=>["manifest.source.js"], "names"=>[]}
-- pre end --
 -- post --
{"version"=>3, "file"=>"manifest.js", "sections"=>[{"offset"=>{"line"=>0, "column"=>0}, "map"=>{"version"=>3, "file"=>"application.js", "mappings"=>";;;AAAA,MAAA,IAAA", "sources"=>["application.source.js"], "names"=>[]}}]}
--
{"version"=>3, "file"=>"manifest.js", "sections"=>[{"offset"=>{"line"=>0, "column"=>0}, "map"=>{"version"=>3, "file"=>"manifest.js", "mappings"=>"", "sources"=>["manifest.source.js"], "names"=>[]}}]}
--post end--
"last_line_count "
    example at ./spec/dummy/spec/request/homepage_spec.rb:19 (FAILED - 1)

Failures:

  1) PagesController get /
     Failure/Error: offset += (last_line_count)

     ActionView::Template::Error:
       nil can't be coerced into Integer
     # /Users/abhinavlele/.gem/ruby/2.5.1/gems/sprockets-4.0.0/lib/sprockets/source_map_utils.rb:96:in `+'
     # /Users/abhinavlele/.gem/ruby/2.5.1/gems/sprockets-4.0.0/lib/sprockets/source_map_utils.rb:96:in `concat_source_maps'
     # /Users/abhinavlele/.gem/ruby/2.5.1/gems/sprockets-4.0.0/lib/sprockets/bundle.rb:108:in `block (2 levels) in process_bundle_reducers'
```

Modified files for tracing the problem - 

`source_map_utils.rb`  

```
 def concat_source_maps(a, b)

      return a || b unless a && b

      puts " -- pre --"
      puts a if a['file'].exclude? 'scss'
      puts " --- "
      puts b if b['file'].exclude? 'scss'
      puts "-- pre end --"
      a = make_index_map(a)
      b = make_index_map(b)
      puts " -- post --"
      puts a if a['file'].exclude? 'scss'
      puts "--"
      puts b if b['file'].exclude? 'scss'
      puts "--post end--"

      offset = 0
      if a["sections"].count != 0 && !a["sections"].last["map"]["mappings"].empty?
```
`bundle.rb`
```
    def self.process_bundle_reducers(input, assets, reducers)
      initial = {}
      reducers.each do |k, (v, _)|
        if v.respond_to?(:call)
          initial[k] = v.call(input)
        elsif !v.nil?
          initial[k] = v
        end
      end

      assets.reduce(initial) do |h, asset|
        p "## reducer #{h} -- #{asset.inspect}"
        tp = TracePoint.new(:call) do |tp|
          p [tp.path, tp.lineno, tp.defined_class, tp.method_id, tp.event].join(' ') if tp.path.include? 'source_map_utils'
        end
        tpr = TracePoint.new(:return) do |tp|
          p [tp.path, tp.lineno, tp.defined_class, tp.method_id, tp.event, tp.return_value].join(' ') if tp.path.include? 'source_map_utils'
        end
        if asset.filename.include?('application')
          puts "----- trace begin -----"
          tp.enable
          tpr.enable
        end
        reducers.each do |k, (_, block)|
          value = k == :data ? asset.source : asset.metadata[k]
          if h.key?(k)
            if !value.nil?
              p "##reduceif #{k} #{block.inspect}"
              h[k] = block.call(h[k], value)
            end
          else
            h[k] = value
          end
        end
        if asset.filename.include?('application')
          puts "----- trace end -----"
          tp.disable
          tpr.disable
        end
        h
      end
    end
  end
```

### System configuration

- Sprockets version 4.0.0
- Ruby version 2.5.1

**Comment by leleabhinav** [comment]
A quick and dirty fix is where I set `last_line_count = 0` when it is `nil`. Can someone with better understanding of `sprockets` comment on some ideas of how this can be backtraced to the root cause, to fix it in a more elegant way?

**Comment by jeremycole** [comment]
FWIW: I think I ran into this same problem with sprockets 4.0.0 and had to pin the version at 3.7.2. In https://github.com/Shopify/explainify this manifests as `ActionView::Template::Error: nil can't be coerced into Integer` on `<%= javascript_include_tag 'application' %>`.

**Comment by leleabhinav** [comment]
Closing this, as the newer release fixes it.
