### ISSUE TITLE
Sprockets 4.0: alternative CSS processors?

### ISSUE THREAD

**Issue by dometto** [rails/sprockets#661]
Is it still possible to use a different CSS processor than SASSC on Sprockets 4.0? It looks like Sprockets will try to load `sassc` even when an alternative processor is specified. When I try to use either `:yui` or `:sass`, I get the following error:

```
2019-12-30 16:47:40 - LoadError - no such file to load -- sassc:
	org/jruby/RubyKernel.java:970:in `require'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/autoload/sassc.rb:2:in `<main>'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/sassc_processor.rb:1:in `(root)'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/sassc_processor.rb:42:in `initialize'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/sassc_processor.rb:27:in `instance'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/sassc_processor.rb:31:in `call'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `block in call_processor'
	org/jruby/RubyArray.java:1885:in `reverse_each'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `call_processors'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `block in call_processors'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:22:in `CompositeProcessor'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:33:in `call'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `block in call_processor'
	org/jruby/RubyArray.java:1885:in `reverse_each'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `call_processors'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/loader.rb:182:in `block in load_from_unloaded'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/loader.rb:59:in `load'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/loader.rb:335:in `fetch_asset_from_dependency_cache'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/loader.rb:43:in `load'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/cached_environment.rb:44:in `load'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/bundle.rb:27:in `call'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `block in call_processor'
	org/jruby/RubyArray.java:1885:in `reverse_each'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `call_processors'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/loader.rb:182:in `block in load_from_unloaded'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/loader.rb:59:in `load'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/loader.rb:335:in `fetch_asset_from_dependency_cache'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/loader.rb:43:in `load'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/cached_environment.rb:44:in `load'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/base.rb:81:in `find_asset'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/environment.rb:31:in `find_asset'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-4.0.0/lib/sprockets/base.rb:119:in `[]'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-helpers-1.2.1/lib/sprockets/helpers.rb:351:in `find_asset_path'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-helpers-1.2.1/lib/sprockets/helpers.rb:145:in `asset_path'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-helpers-1.2.1/lib/sprockets/helpers.rb:158:in `asset_tag'
	~/.rvm/gems/jruby-9.2.0.0@gollum/gems/sprockets-helpers-1.2.1/lib/sprockets/helpers.rb:180:in `block in stylesheet_tag'
```

Sprockets environment:

```ruby
  module Assets
    MANIFEST = %w(app.js editor.js app.css criticmarkup.css fileview.css ie7.css print.css *.png *.jpg *.svg *.eot *.ttf *.woff *.woff2)
    ASSET_URL = 'gollum/assets'
    
    def self.sprockets(dir = File.dirname(File.expand_path(__FILE__)))
      env = Sprockets::Environment.new
      env.append_path ::File.join(dir, 'public/gollum/stylesheets/')
      env.append_path ::File.join(dir, 'public/gollum/javascript')
      env.append_path ::File.join(dir, 'public/gollum/images')
      env.append_path ::File.join(dir, 'public/gollum/fonts')

      env.js_compressor  = :uglify
      env.css_compressor = :yui

      env
    end
  end
end
```

## Example app

As you can see I'm trying to get this to run with gollum, which uses sinatra and not Rails. Example branch: https://github.com/repotag/gollum/tree/sprockets-example

To run: `bundle install && bundle exec gollum path/to/repo`, visit `http://127.0.0.1:4567`

**Comment by ahorek** [comment]
in sprockets 4 sassc is the default transformer. sass gem should still work, but you have to register it manually https://github.com/rails/sprockets/commit/33d0a6f2e4e1c8f3b5673d8eac3abdad9f6825c0

note that sass gem is no longer maintained https://sass-lang.com/blog/ruby-sass-is-deprecated

:yui is just a compressor, but you still need a `sass > css` transformer, an alternative could be https://github.com/sass/dart-sass but there's no integration for ruby (yet)

for now, sassc is the only reasonable option

**Comment by ntkme** [comment]
A drop-in solution that replaces sassc with sass-embedded: https://github.com/ntkme/sassc-embedded-polyfill-ruby

**Comment by jacob-carlborg-apoex** [comment]
If you want to use Sass, you can use https://github.com/rails/dartsass-rails. Seems to be the new preferred way to integrate Sass into a Rails application. I ran into the same issue when trying to use dartsass-rails. The solution was to remove any referenced CSS files from the manifest file (`app/assets/config/manifest.js`), see https://github.com/rails/dartsass-rails/issues/12.

**Comment by rafaelfranca** [comment]
Yes, You can register alternative CSS processors, you just need to do it using https://github.com/rails/sprockets/blob/main/lib/sprockets.rb#L172-L173

**Comment by dometto** [comment]
> A drop-in solution that replaces sassc with sass-embedded (dart-sass-embedded): https://github.com/ntkme/sassc-embedded-shim-ruby

Thanks @ntkme!
